FROM ubuntu:22.04

ARG UID=1000
RUN useradd -m -u ${UID} -s /bin/bash builder

# Non-interactive configuration of tzdata
#ENV DEBIAN_FRONTEND noninteractive
#ENV DEBCONF_NONINTERACTIVE_SEEN true
RUN { echo 'tzdata tzdata/Areas select Etc'; echo 'tzdata tzdata/Zones/Etc select UTC'; } | debconf-set-selections

RUN apt-get update
RUN apt-get install -y cmake gdb
