FROM darvik80/crosstool-base:latest

RUN apt-get install -y gcc g++ gperf bison flex texinfo help2man make libncurses5-dev \
    python3-dev autoconf automake libtool libtool-bin gawk wget bzip2 xz-utils unzip \
    patch libstdc++6 rsync git meson ninja-build mc htop openssh-server build-essential cmake gdb wget

USER builder
WORKDIR /home/builder
RUN git clone https://github.com/crosstool-ng/crosstool-ng
WORKDIR /home/builder/crosstool-ng
RUN ./bootstrap
RUN ./configure --enable-local
RUN make
