FROM darvik80/builder-ng:latest

USER root
RUN apt install -y python3 python3-pip wget mc git
RUN pip3 install conan

USER builder
WORKDIR /home/builder
RUN wget --no-check-certificate https://boostorg.jfrog.io/artifactory/main/release/1.81.0/source/boost_1_81_0.tar.gz
RUN tar -xf boost_1_81_0.tar.gz

WORKDIR /home/builder/boost_1_81_0
RUN ./bootstrap.sh
RUN echo "using gcc : arm : armv7-rpi2-linux-gnueabihf-g++  ;" >> user-config.jam
RUN ./b2 toolset=gcc-arm --user-config=./user-config.jam address-model=32 architecture=arm link=static
USER root
RUN ./b2 install --prefix=/opt


# build json
USER builder
WORKDIR /home/builder
RUN git clone https://github.com/nlohmann/json.git
WORKDIR /home/builder/json/build
RUN cmake -DCMAKE_INSTALL_PREFIX=/opt ../
RUN make
USER root
RUN make install

# build libfmt
USER builder
WORKDIR /home/builder
RUN git clone https://github.com/fmtlib/fmt.git
WORKDIR /home/builder/fmt/build
RUN cmake -DCMAKE_INSTALL_PREFIX=/opt ../
RUN make
USER root
RUN make install

USER builder
WORKDIR /home/builder
ENTRYPOINT ["/bin/bash", "--"]