FROM ubuntu:22.04 AS Ubuntu

ARG UID=1000
RUN useradd -m -u ${UID} -s /bin/bash builder

# Non-interactive configuration of tzdata
#ENV DEBIAN_FRONTEND noninteractive
#ENV DEBCONF_NONINTERACTIVE_SEEN true
RUN { echo 'tzdata tzdata/Areas select Etc'; echo 'tzdata tzdata/Zones/Etc select UTC'; } | debconf-set-selections

RUN apt-get update && apt-get install -y cmake gdb


FROM Ubuntu AS CrossToolNG

RUN apt-get install -y gcc g++ gperf bison flex texinfo help2man make libncurses5-dev \
    python3-dev autoconf automake libtool libtool-bin gawk wget bzip2 xz-utils unzip \
    patch libstdc++6 rsync git meson ninja-build mc htop openssh-server build-essential cmake gdb

USER builder
WORKDIR /home/builder
RUN git clone https://github.com/crosstool-ng/crosstool-ng
WORKDIR /home/builder/crosstool-ng
RUN ./bootstrap
RUN ./configure --enable-local
RUN make
RUN ./ct-ng armv7-rpi2-linux-gnueabihf
RUN ./ct-ng build

FROM Ubuntu AS Builder

WORKDIR /home/builder
COPY --from=CrossToolNG /home/builder/x-tools/armv7-rpi2-linux-gnueabihf /usr/local

USER builder
ENV PATH="/usr/local/bin:$PATH"
ENV CC="/usr/local/bin/armv7-rpi2-linux-gnueabihf-gcc"
ENV CXX="/usr/local/bin/armv7-rpi2-linux-gnueabihf-g++"

ENTRYPOINT ["/bin/bash", "--"]